pgdog.toml, pgdog/src/backend/databases.rs, pgdog/src/cli.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/router/parser/csv_buffer.rs, pgdog/src/frontend/router/parser/mod.rs, pgdog/src/frontend/router/parser/order_by.rs, pgdog/src/frontend/router/parser/query.rs, pgdog/src/frontend/router/parser/where_clause.rs, pgdog/src/main.rs, pgdog/src/net/messages/bind.rs, pgdog/tests/pypg.py, pgdog/tests/rails_schema_cache.txt, pgdog/tests/rails_tests.rb
Add support for automatically detecting sharding columns in SELECT statements and routing them to the right shards. Supports both simple and extended protocols. Prepared statements are TODO.
=> Sharded SELECT queries

pgdog/Cargo.toml, pgdog/src/backend/mod.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/backend/pool/mod.rs, pgdog/src/backend/pool/monitor.rs, pgdog/src/backend/pool/test/mod.rs, pgdog/src/backend/schema/mod.rs, pgdog/src/backend/schema/queries.rs, pgdog/src/backend/schema/tables.sql, pgdog/src/cli.rs, pgdog/src/config/error.rs, pgdog/src/config/mod.rs, pgdog/src/config/overrides.rs, pgdog/src/config/url.rs, pgdog/src/frontend/router/parser/csv/iterator.rs, pgdog/src/frontend/router/parser/csv/record.rs, pgdog/src/frontend/router/parser/query.rs, pgdog/src/frontend/router/parser/value.rs, pgdog/src/main.rs
- Fetch schema from database. This will be used later for automatic sharding.
- Add `-d / --database-url` launch option to configure database connections from a list of URLs. This avoids having to specify `pgdog.toml` and `users.toml`
- Add optional `--min-pool-size`, `--pool-size` and `--session-mode` to CLI to override values in `pgdog.toml`.
Fix pool not replenishing connections to maintain `min_pool_size` when idle connections are present.
=> Schema loading & database-url

pgdog/src/frontend/client.rs, pgdog/src/frontend/listener.rs, pgdog/src/net/discovery/listener.rs, pgdog/src/net/messages/error_response.rs
Allow admin connections during shutdown so monitoring tools like DataDog can collect stats while we wait for slow clients to shutdown.
Send graceful error message to regular clients that connect while the pooler is shutting down.
=> Allow admin connections during shutdown

pgdog/src/admin/mod.rs, pgdog/src/admin/parser.rs, pgdog/src/admin/prelude.rs, pgdog/src/admin/reset_query_cache.rs, pgdog/src/admin/show_query_cache.rs, pgdog/src/frontend/router/parser/cache.rs
- Add `SHOW QUERY_CACHE` admin command to list queries stored in the query parser cache.
- Track hit and miss rates globally and on each query in the query cache.
- Add `RESET QUERY_CACHE` to remove all queries from the cache.
=> Show query cache

pgdog/src/frontend/client/mod.rs
As `QueryLogger` is only available in debug mode, ran into issue while
compiling `PgDog` in `release` mode:
`cargo build --release`
```
error[E0432]: unresolved import `crate::frontend::QueryLogger`
--> pgdog/src/frontend/client/mod.rs:13:5
|
13 | use crate::frontend::QueryLogger;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `QueryLogger` in `frontend`
|
note: found an item that was configured out
--> pgdog/src/frontend/mod.rs:22:23
|
22 | pub use query_logger::QueryLogger;
|                       ^^^^^^^^^^^
note: the item is gated here
--> pgdog/src/frontend/mod.rs:21:1
|
21 | #[cfg(debug_assertions)]
| ^^^^^^^^^^^^^^^^^^^^^^^^
For more information about this error, try `rustc --explain E0432`.
error: could not compile `pgdog` (bin "pgdog") due to 1 previous error
```
=> fix: Update frontend/client/mod.rs with conditional module import in debug build

pgdog/src/backend/databases.rs, pgdog/src/backend/pool/connection/buffer.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/backend/pool/connection/multi_shard.rs, pgdog/src/backend/server.rs, pgdog/src/frontend/router/parser/aggregate.rs, pgdog/src/frontend/router/parser/mod.rs, pgdog/src/frontend/router/parser/query.rs, pgdog/src/frontend/router/parser/route.rs, pgdog/src/net/messages/data_row.rs, pgdog/src/net/messages/data_types/interval.rs, pgdog/src/net/messages/data_types/mod.rs, pgdog/src/net/messages/data_types/numeric.rs, pgdog/src/net/messages/data_types/timestamp.rs, pgdog/src/net/messages/data_types/timestamptz.rs, pgdog/src/net/messages/data_types/uuid.rs
Add support for basic usage of `COUNT(*)`, `MAX(column)`, and `MIN(column)`. Things that don't work yet:
- `GROUP BY`
- Processing supported and unsupported aggregates in the same query
```sql
SELECT COUNT(*), MIN(id), MAX(id) FROM users;
```
Related: #40
=> Support for basic count(*), min, max functions

pgdog/src/backend/pool/connection/aggregate.rs, pgdog/src/backend/pool/connection/buffer.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/frontend/router/parser/aggregate.rs, pgdog/src/frontend/router/parser/mod.rs, pgdog/src/frontend/router/parser/route.rs, pgdog/src/net/messages/data_row.rs, pgdog/src/net/messages/data_types/interval.rs, pgdog/src/net/messages/data_types/mod.rs, pgdog/src/net/messages/data_types/numeric.rs, pgdog/src/net/messages/data_types/timestamp.rs, pgdog/src/net/messages/data_types/timestamptz.rs, pgdog/src/net/messages/data_types/uuid.rs
- Add `GROUP BY` support to aggregates. This works currently without rewriting queries, so the `GROUP BY` clause must use references to columns present in the result, e.g. `GROUP BY 3, 4`.
- Support NULLs in `DataRow` message building.
#40
=> Add limited GROUP BY support

pgdog/src/backend/server.rs, pgdog/src/frontend/buffer.rs, pgdog/src/frontend/prepared_statements/global_cache.rs, pgdog/src/frontend/prepared_statements/mod.rs, pgdog/src/frontend/prepared_statements/rewrite.rs, pgdog/src/frontend/router/parser/query.rs, pgdog/src/net/messages/parse.rs
- Use `Arc` in Parse to avoid unnecessary re-allocations when checking the prepared statement cache.
=> Reduce allocs around prepared statements cache

integration/rust/tests/tokio_postgres/mod.rs, integration/rust/tests/tokio_postgres/prepared.rs, pgdog/src/backend/server.rs, pgdog/src/frontend/client/mod.rs
- Clearing params triggers a reset on the client.
=> Fix up params some more

integration/toxi/rspec_helper.rb, integration/toxi/toxi_spec.rb, pgdog/src/backend/pool/inner.rs, pgdog/src/backend/pool/pool_impl.rs, pgdog/src/backend/pool/shard.rs, pgdog/src/frontend/client/mod.rs, pgdog/src/frontend/router/parser/query.rs
- Bypass ban for primary pool if it's a write.
- Add ActiveRecord tests
- Route `SET` queries to replicas (no primary requirement for running Rails)
=> Use replicas

pgdog/src/backend/pool/pool_impl.rs, pgdog/src/backend/server.rs
- Respect manual ban in primary unban logic.
- Remove hardcoded localhost address from query cancellation.
=> Respect manual bans

integration/complex/passthrough_auth/run.sh, integration/complex/passthrough_auth/users.toml, integration/rust/tests/sqlx/bad_auth.rs, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/address.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/backend/pool/config.rs, pgdog/src/config/convert.rs, pgdog/src/config/mod.rs, pgdog/src/config/url.rs, pgdog/src/frontend/client/mod.rs, users.toml
- Passthrough auth users can be specified in `users.toml` without the password. User settings will be picked up as if the user had a password.
- All user-specific settings can be now be specified on the database in `pgdog.toml`. User settings continue to take highest priority, database settings are next, and general settings are lowest priority.
=> Allow empty passwords

.github/workflows/package.yml
Based on the example Github Actions workflow [here](https://docs.docker.com/build/ci/github-actions/multi-platform/).
=> Build arm64 and amd64 images

examples/mastodon/fk.py, integration/dev-server.sh, integration/rust/Cargo.toml, integration/rust/src/setup.rs, integration/rust/tests/integration/fake_transactions.rs, integration/rust/tests/integration/reload.rs, pgdog.toml, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/backend/pool/config.rs, pgdog/src/backend/pool/inner.rs, pgdog/src/backend/pool/pool_impl.rs, pgdog/src/backend/pool/replicas.rs, pgdog/src/backend/pool/shard.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/listener.rs, pgdog/src/main.rs, pgdog/src/sighup.rs
- Preserve server connections when reloading config with no cluster topology changes.
- Listen for `SIGHUP` and reload config.
=> Save server connections on reload

.github/workflows/ci.yml, pgdog.toml, pgdog/src/backend/pool/connection/binding.rs, pgdog/src/frontend/client/mod.rs, pgdog/src/net/stream.rs
- Release server connection back into the pool before doing I/O.
- Don't allocate a `Vec` for multi-shard transactions.
- Ensure the message we receive is at least 4 bytes long (as per spec).
=> Release connection before doing I/O

pgdog/src/frontend/prepared_statements/global_cache.rs, pgdog/src/net/messages/parse.rs
- Remove memory allocations from parsing `Parse` messages.
=> Remove memory allocations from Parse

pgdog.toml, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/backend/pool/connection/binding.rs, pgdog/src/backend/pool/connection/mirror.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/backend/server.rs, pgdog/src/backend/stats.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/client/inner.rs, pgdog/src/frontend/client/mod.rs, pgdog/src/frontend/listener.rs, pgdog/src/frontend/router/mod.rs, pgdog/src/state.rs, pgdog/tests/pgbench.sh, users.toml
Allow for databases to mirror traffic from other databases. This allows testing different databases with production traffic.
=> Mirroring traffic

.github/workflows/package.yml
Reverts pgdogdev/pgdog#133
I'm getting exec format errors pulling fresh images from GitHub. I suspect we're not pushing them correctly.
=> Revert "Add ARM64 build"

pgdog/src/backend/databases.rs, pgdog/src/backend/mod.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/backend/reload_notify.rs
- Config reloads weren't atomic, causing some clients to hit offline pools. Fixed with a combination of Notify and AtomicBool.
=> Fix reload

pgdog/src/backend/pool/connection/mirror.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/client/mod.rs
- Make `auth_type` configurable. If your app makes lots of new connections and is latency sensitive, use `md5`. Otherwise, `scram` works it's just pretty slow (on purpose).
- Check for all replicas down in mirror.
=> Make auth type configurable

integration/rust/tests/integration/auth.rs, integration/rust/tests/integration/mod.rs, integration/rust/tests/sqlx/bad_auth.rs, pgdog/src/admin/error.rs, pgdog/src/admin/parser.rs, pgdog/src/admin/set.rs, pgdog/src/backend/databases.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/client/mod.rs
- Fix #148 
- Enable `SET` admin database command to modify some settings at runtime. This is mostly for testing, I wouldn't use it in prod because the changes don't persist across restarts.
=> Trust auth

integration/pgbench/dev.sh, integration/rust/tests/integration/reload.rs, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/config/convert.rs, pgdog/src/frontend/client/mod.rs, pgdog/src/frontend/router/parser/command.rs, pgdog/src/frontend/router/parser/query.rs, pgdog/src/net/messages/hello.rs, pgdog/src/net/parameter.rs
#157 
When the first query inside a transaction is `SET`, send the transaction to the primary. PgDog needs to execute this query, but we don't have enough information on whether the transaction will read or write. To be safe, send it to the primary.
This PR also makes PgDog handle `SET` queries internally without assigning them to a server. Until a client runs an actual query.
=> Send SET queries to primary

pgdog.toml, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/backend/pool/connection/mirror.rs, pgdog/src/backend/schema/mod.rs, pgdog/src/backend/schema/relation.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/client/inner.rs, pgdog/src/frontend/client/mod.rs, pgdog/src/frontend/mod.rs, pgdog/src/frontend/router/context.rs, pgdog/src/frontend/router/mod.rs, pgdog/src/frontend/router/parser/error.rs, pgdog/src/frontend/router/parser/key.rs, pgdog/src/frontend/router/parser/mod.rs, pgdog/src/frontend/router/parser/multi_tenant.rs, pgdog/src/frontend/router/parser/query.rs, pgdog/src/frontend/router/parser/route.rs, pgdog/src/frontend/router/parser/table.rs, pgdog/src/frontend/router/parser/where_clause.rs, pgdog/src/frontend/router/search_path.rs
- Support for checking `tenant_id` on all queries that touch tables with that column. The column is configurable in `pgdog.toml`. This protects the app from forgetting to include the tenant ID in a query.
- Fix bug around routing `SET` inside a transaction: if the cluster is read-only, send it to a replica. #162
=> Multi-tenant

pgdog/src/main.rs, pgdog/src/stats/logger.rs, pgdog/src/stats/mod.rs
When in dry run mode, log query cache stats directly to console so it's easier to debug (no monitoring agent required).
=> Log query cache stats in dry run mode

CONTRIBUTING.md
Add some information about how to spin up and successfully run the test suite.
Consistently use '.' to end bulleted sentences.
=> Adding some information about getting the test suite to run locally

examples/demo/src/main.rs, pgdog.toml, pgdog/src/config/mod.rs, pgdog/src/stats/open_metric.rs
- Add `openmetrics_namespace` option to namespace metrics.
- Remove warnings.
=> Openmetrics prefix

integration/pgdog.toml, integration/python/globals.py, integration/rust/tests/integration/ban.rs, integration/rust/tests/integration/mod.rs, pgdog/src/admin/ban.rs, pgdog/src/admin/mod.rs, pgdog/src/admin/parser.rs, pgdog/src/admin/show_pools.rs, pgdog/src/backend/error.rs, pgdog/src/backend/pool/inner.rs, pgdog/src/backend/pool/pool_impl.rs, pgdog/src/backend/pool/replicas.rs, pgdog/src/backend/pool/test/mod.rs, pgdog/src/backend/pool/test/replica.rs, pgdog/src/backend/prepared_statements.rs, pgdog/src/backend/server.rs, pgdog/src/frontend/client/mod.rs
- Don't disconnect client if pool is banned. Let them  run the query again on a different pool.
- Add admin ban/unban commands to ban specific pools (or all of them).
- Show pool id in `SHOW POOLS`.
- Fix suspected out of sync in #134.
=> Manual ban/unban

integration/rust/tests/integration/fake_transactions.rs, pgdog/src/config/mod.rs, pgdog/src/config/url.rs, pgdog/src/main.rs
- Don't override settings in `pgdog.toml` when using `--database-url/-d` option.
=> Dont override settings when using -d

pgdog/src/backend/pool/cluster.rs, pgdog/src/frontend/router/parser/query.rs
Set shard to 0 when database isn't sharded and the client doesn't have a query in the buffer (e.g. prepared stmt close).
=> Do single-shard routing when no routing info available

integration/go/go_pgx/sharded_test.go, pgdog.toml, pgdog/src/frontend/router/parser/insert.rs, pgdog/src/frontend/router/parser/key.rs, pgdog/src/frontend/router/parser/query.rs, pgdog/src/frontend/router/parser/where_clause.rs, pgdog/src/frontend/router/sharding/context_builder.rs, pgdog/src/net/error.rs, pgdog/src/net/messages/data_types/array.rs, pgdog/src/net/messages/data_types/mod.rs
If caller is using `WHERE sharding_key = ANY($1)`, send the query to all shards.
TODO: parse the `$1` parameter and hash each key. 99% of the time, this will go to all shards anyway, but it's still worth doing.
=> Send ANY($1) to all shards

integration/go/go_pgx/sharded_test.go, integration/pgdog.toml, integration/setup.sh, pgdog.toml, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/client/mod.rs, pgdog/src/frontend/router/mod.rs, pgdog/src/frontend/router/parser/route.rs, pgdog/src/frontend/router/sharding/context.rs, pgdog/src/frontend/router/sharding/context_builder.rs, pgdog/src/frontend/router/sharding/list.rs, pgdog/src/frontend/router/sharding/mod.rs, pgdog/src/frontend/router/sharding/operator.rs, pgdog/src/frontend/router/sharding/range.rs, pgdog/src/frontend/router/sharding/test/mod.rs, pgdog/src/frontend/router/sharding/value.rs, pgdog/src/net/messages/error_response.rs
1. Add support for range-based and list-based sharding.
2. Add setting to disable cross-shard queries.
```toml
[[sharded_tables]]
name = "my_table"
data_type = "bigint"
column = "id"
[[sharded_mappings]]
table = "my_table"
column = "id"
kind = "range"
start = 0
end = 100
shard = 0
[[sharded_mappings]]
table = "my_table"
column = "id"
kind = "range"
start = 100
end = 200
shard = 1
```
```toml
[[sharded_tables]]
name = "my_table"
data_type = "bigint"
column = "id"
[[sharded_mappings]]
table = "my_table"
column = "id"
kind = "list"
values = [1, 2, 3, 4, 5]
shard = 0
```
```toml
[general]
cross_shard_disabled = true
```
=> List and range based sharding

pgdog/src/backend/pool/ban.rs, pgdog/src/backend/pool/config.rs, pgdog/src/backend/pool/error.rs, pgdog/src/backend/pool/inner.rs, pgdog/src/backend/pool/monitor.rs, pgdog/src/backend/pool/pool_impl.rs, pgdog/src/config/mod.rs
Add `connect_attempts` and `connect_attempt_delay` settings. The first allows to retry creating new server connections without banning a host. As long as `checkout_timeout` is longer than `connect_timeout`.
=> Connection retries

pgdog/src/cli.rs
- Add --version flag that displays "PgDog v{GIT_HASH}"
Closes #250
=> Addd --version CLI flag using clap built-in macro

integration/rust/tests/integration/auth.rs, pgdog/src/admin/set.rs, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/connection/mirror.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/config/convert.rs, pgdog/src/frontend/client/inner.rs, pgdog/src/frontend/client/mod.rs
- Re-create pools created with passthrough load on config reload.
- Don't create connection pools for admin connections via passthrough auth. They aren't used by clients and could log errors if the admin user doesn't exist in Postgres.
=> Preserve passthrough auth users on reload

pgdog/src/backend/pool/connection/mod.rs, pgdog/src/frontend/client/inner.rs, pgdog/src/frontend/router/mod.rs, pgdog/src/frontend/router/parser/query.rs
- renamed `replication_mode` to `enter_replication_mode()` given that `replication_mode()` reads like a getter, not a setter.
- Split and Grouped QueryParser methods logically to process the file in smaller mental chunks. (helps LLMs too).
- No logical changes, exact same function content, just moved.
=> Refactor :: Group QueryParser processing steps logically.

pgdog/src/stats/open_metric.rs
Adjust TYPE, UNIT, and HINT metric name to match when using prefix to support google cloud prometheus metric ingestion
https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#unknown-double-written
=> Adjust Labels to match metric names when using prefix

pgdog/src/backend/pool/inner.rs
- clear idle_connections on `maybe_ban`
- test_maybe_ban_clears_idle_connections()
- renamed conns to `idle_connections`
- renamed `id` to `client_id`, especially because it returns an `id`
=> Close pool.idle_connections on pool banned.

integration/mirror/pgdog.toml, integration/mirror/users.toml, integration/setup.sh, pgdog/src/backend/error.rs, pgdog/src/backend/pool/cluster.rs, pgdog/src/backend/pool/connection/binding.rs, pgdog/src/backend/pool/connection/mirror.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/backend/pool/connection/multi_shard/mod.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/buffer.rs, pgdog/src/frontend/client/mod.rs
- Buffer entire transactions to help with realism and reduce errors.
- Record timings between queries to simulate idle sessions.
- Add `mirror_exposure` setting allowing to send a percentage of traffic to the mirrors.
- Remove dead code in `Buffer`.
- Use `Deref` for `Binding` instead of duplicating code.
=> [Mirroring] Buffer entire transactions & add exposure setting

pgdog/src/backend/pool/shard.rs, pgdog/src/backend/replication/logical/publisher/queries.rs, pgdog/src/backend/schema/mod.rs, pgdog/src/backend/schema/sync/error.rs, pgdog/src/backend/schema/sync/mod.rs, pgdog/src/backend/schema/sync/pg_dump.rs, pgdog/src/cli.rs, pgdog/src/config/mod.rs, pgdog/src/lib.rs, pgdog/src/main.rs
Sync schema between source and destination clusters. Uses shard 0 of the source cluster as schema source. Only the following objects are synced:
- Table columns and data types
- Primary key constraint
- Sequences
What's ignored (for now):
- Foreign keys
- Unique indexes
This is on purpose, as to accelerate data sync. Those objects will be added after sync is complete.
Continuation of #279.
=> [Resharding] Schema sync

pgdog/CLAUDE.md, pgdog/src/config/mod.rs, pgdog/src/frontend/router/parser/context.rs
Disable prepared statements globally if pooler mode is set to session _globally_. We don't have a prepared statements configuration on a user/database level. (TODO: probably should add it) #295
=> Disable prepared statements in session mode

.github/workflows/package.yml
- Add Git commit hash as a tag to Docker images
=> Add hash to docker tag

.gitignore, integration/load_balancer/pgx/read_write_split_test.go, pgdog-plugin-build/src/lib.rs, pgdog/src/admin/mod.rs, pgdog/src/admin/server.rs, pgdog/src/backend/pool/connection/binding.rs, pgdog/src/backend/pool/connection/buffer.rs, pgdog/src/backend/pool/connection/mod.rs, pgdog/src/backend/pool/connection/multi_shard/mod.rs, pgdog/src/backend/pool/test/mod.rs, pgdog/src/backend/pool/test/replica.rs, pgdog/src/config/mod.rs, pgdog/src/frontend/client/query_engine/connect.rs, pgdog/src/frontend/client/query_engine/mod.rs, pgdog/src/frontend/client/query_engine/query.rs, pgdog/src/frontend/client/query_engine/route_query.rs, pgdog/src/frontend/client/query_engine/set.rs, pgdog/src/frontend/client/test/mod.rs, pgdog/src/frontend/client_request.rs, pgdog/src/frontend/router/context.rs, pgdog/src/frontend/router/mod.rs, pgdog/src/frontend/router/parser/command.rs, pgdog/src/frontend/router/parser/context.rs, pgdog/src/frontend/router/parser/limit.rs, pgdog/src/frontend/router/parser/order_by.rs, pgdog/src/frontend/router/parser/query/mod.rs, pgdog/src/frontend/router/parser/query/set.rs, pgdog/src/frontend/router/parser/query/test.rs, pgdog/src/frontend/router/parser/route.rs
Per-statement routing. Handles direct-to-shard queries inside cross-shard transactions.
1. `BEGIN READ ONLY`  transactions are sent to replicas.
2. `BEGIN` transactions are sent to the primary, unless `read_write_strategy = "aggressive"`, in which case the first statement inside the transaction is used for routing.
3. Each statement inside a transaction is evaluated and routed to one or more shards. This allows for cross-shard and direct-to-shard queries inside the same transaction!
Added some tests to validate.
=> Per-statement routing

pgdog/src/backend/databases.rs, pgdog/src/frontend/client/query_engine/end_transaction.rs
Primary fix: Mirrors are set up by database name, but no user check is in place. This PR makes the key for a mirror a User, to ensure that source and destination databases always use the same username.
Secondary fix: Transaction state isn't closed out when transactions end, causing flush not to be called at the end of every transaction.
=> Fix Mirroring assignment issue

pgdog/src/frontend/client/mod.rs, pgdog/src/frontend/client/query_engine/mod.rs, pgdog/src/frontend/comms.rs
- Pause clients only, not mirrors, when enabling maintenance mode.
=> Pause clients, not mirrors for maintenance mode

pgdog/src/backend/schema/sync/pg_dump.rs
Passed the wrong source text to pg_dump's output handler.
=> Fix pg_dump clean typo

pgdog/src/frontend/router/parser/aggregate.rs
found this bug while working to implement `avg()`
=> fix: correct aggregate function matching in parser

pgdog/src/frontend/client/query_engine/incomplete_requests.rs, pgdog/src/frontend/client/query_engine/mod.rs, pgdog/src/frontend/client/query_engine/prepared_statements.rs, pgdog/src/frontend/client/test/mod.rs, pgdog/src/frontend/prepared_statements/rewrite.rs, pgdog/src/net/protocol_message.rs
Handle Close message in the order it was received. Clients sometimes close a prepared statement with the same name as they are preparing, in the same request. Previously, we handled Close before/after the request, which disrupted the order of operations. Now, we're handling it in the order it was sent by the client.
=> Handle Close in order it was received

pgdog/src/auth/gssapi/context.rs, pgdog/src/auth/gssapi/error.rs, pgdog/src/auth/gssapi/mod.rs, pgdog/src/auth/gssapi/server.rs, pgdog/src/auth/gssapi/ticket_cache.rs, pgdog/src/auth/gssapi/ticket_manager.rs, pgdog/src/backend/server.rs, pgdog/tests/backend_gssapi_test.rs, pgdog/tests/gssapi_integration_test.rs
- Lowercase errors
- Don't log error when we return it
- Keytab command is async now, wont block tokio in case of cache miss
- Use thiserror
=> A few fixes

Cargo.lock, pgdog/Cargo.toml, pgdog/src/admin/set.rs, pgdog/src/admin/show_prepared_statements.rs, pgdog/src/admin/show_query_cache.rs, pgdog/src/backend/databases.rs, pgdog/src/backend/pool/connection/multi_shard/mod.rs, pgdog/src/backend/prepared_statements.rs, pgdog/src/backend/server.rs, pgdog/src/frontend/client/test/mod.rs, pgdog/src/frontend/client_request.rs, pgdog/src/frontend/prepared_statements/mod.rs, pgdog/src/frontend/prepared_statements/rewrite.rs, pgdog/src/frontend/router/parser/cache.rs, pgdog/src/frontend/router/parser/comment.rs, pgdog/src/frontend/router/parser/error.rs, pgdog/src/frontend/router/parser/query/mod.rs, pgdog/src/frontend/router/parser/query/test.rs, pgdog/src/net/decoder.rs, pgdog/src/stats/query_cache.rs
- Fix #477 
- Use `RwLock` with prepared statements cache to decrease contention
=> Add /* pgdog_role */ comment

pgdog/src/admin/show_config.rs, pgdog/src/backend/pool/config.rs, pgdog/src/config/database.rs, pgdog/src/config/general.rs, pgdog/src/config/users.rs
- Make connection max age configurable. 
- Fix `idle_timeout` user setting taking priority over database setting (it should be inverse).
=> server_lifetime setting

pgdog/src/backend/databases.rs, pgdog/src/backend/pool/config.rs
- Disable banning when database cluster has only one database, e.g., a primary or a replica. Banning produces confusing errors when load balancer isn't actually used.
=> Disable LB host banning when no alternative targets available

Cargo.lock, pgdog/Cargo.toml, pgdog/src/backend/databases.rs, pgdog/src/config/core.rs, pgdog/src/config/url.rs, pgdog/src/config/users.rs
Fix #521 
This allows configuring the admin section in `users.toml`, which will override admin set in `pgdog.toml`, if any.
=> Override admin in pgdog.toml with admin in users.toml

pgdog/src/frontend/router/parser/query/explain.rs, pgdog/src/frontend/router/parser/query/mod.rs, pgdog/src/frontend/router/parser/query/select.rs, pgdog/src/frontend/router/parser/rewrite_engine.rs
- Don't parse `SELECT` statement twice when rewriting for ghost columns.
=> Use parsed AST instead of double-parsing SELECT stmt
