- examples/routing-plugin/src/lib.rs
- pgdog-plugin/src/config.rs
- pgdog-plugin/src/plugin.rs
- pgdog-plugin/src/query.rs
- pgdog/src/admin/mod.rs
- pgdog/src/admin/parser.rs
- pgdog/src/admin/reload.rs
- pgdog/src/admin/show_pools.rs
- pgdog/src/backend/pool/guard.rs
- pgdog/src/backend/pool/inner.rs
- pgdog/src/backend/pool/monitor.rs
- pgdog/src/backend/pool/pool.rs
- pgdog/src/backend/pool/replicas.rs
- pgdog/src/backend/pool/shard.rs
- pgdog/src/backend/pool/test/mod.rs
- pgdog/src/frontend/comms.rs
- pgdog/src/net/messages/auth/mod.rs
- pgdog/src/net/messages/data_row.rs
- plugins/pgdog-routing/src/lib.rs
- Fix leaky healthcheck.
- Simplify connection creation logic.
> Some pool fixes

- pgdog-plugin/src/route.rs
- pgdog-sharded.toml
- pgdog/src/backend/databases.rs
- pgdog/src/backend/pool/cleanup.rs
- pgdog/src/backend/pool/cluster.rs
- pgdog/src/backend/pool/connection/binding.rs
- pgdog/src/backend/pool/connection/mod.rs
- pgdog/src/backend/pool/connection/multi_shard.rs
- pgdog/src/backend/pool/pool.rs
- pgdog/src/backend/server.rs
- pgdog/src/cli.rs
- pgdog/src/config/mod.rs
- pgdog/src/net/messages/command_complete.rs
- pgdog/src/net/messages/row_description.rs
- plugins/pgdog-routing/src/lib.rs
- users-sharded.toml
Very basic multi-shard queries.
> Multi-shard queries

- pgdog/src/backend/pool/cluster.rs
- pgdog/src/backend/pool/config.rs
- pgdog/src/backend/pool/monitor.rs
- pgdog/src/backend/pool/pool_impl.rs
- pgdog/src/backend/server.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/buffer.rs
- pgdog/src/frontend/client.rs
- pgdog/src/frontend/router/parser/copy.rs
- pgdog/src/frontend/router/parser/error.rs
- pgdog/src/frontend/router/parser/query.rs
- pgdog/src/net/error.rs
- pgdog/src/net/messages/mod.rs
- pgdog/src/net/stream.rs
Support for passing the replication stream through pgDog. This will allow us to inspect logical replication messages.
> Support for replication

- pgdog.toml
- pgdog/src/backend/server.rs
- pgdog/src/frontend/router/parser/copy.rs
- pgdog/src/net/error.rs
- pgdog/src/net/messages/copy_data.rs
- pgdog/src/net/messages/data_row.rs
- pgdog/src/net/messages/mod.rs
- pgdog/src/net/messages/replication/hot_standby_feedback.rs
- pgdog/src/net/messages/replication/keep_alive.rs
- pgdog/src/net/messages/replication/logical/begin.rs
- pgdog/src/net/messages/replication/logical/commit.rs
- pgdog/src/net/messages/replication/logical/insert.rs
- pgdog/src/net/messages/replication/logical/mod.rs
- pgdog/src/net/messages/replication/logical/relation.rs
- pgdog/src/net/messages/replication/logical/tuple_data.rs
- pgdog/src/net/messages/replication/mod.rs
- pgdog/src/net/messages/replication/status_update.rs
- pgdog/src/net/messages/replication/xlog_data.rs
- pgdog/src/net/messages/row_description.rs
- users.toml
Implement parsing logical replication messages that we'll shard later.
> Parse logical replication stream

- Dockerfile
- README.md
- docker-compose.yml
- docker/pgdog.toml
- docker/setup.sql
- docker/users.toml
- pgdog/src/backend/schema/mod.rs
- pgdog/src/backend/schema/table.rs
- pgdog/src/backend/schema/trigger_function.rs
- pgdog/src/backend/schema/trigger_function.sql
- Add a Docker Compose demo that just works.
- Change Docker container stop signal to INT for graceful shutdown.
- Start thinking about data integrity on the shards (with triggers).
> Docker demo

- pgdog/src/backend/pool/cluster.rs
- pgdog/src/backend/replication/buffer.rs
- pgdog/src/backend/replication/config.rs
- pgdog/src/backend/replication/mod.rs
- pgdog/src/backend/replication/sharded_tables.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/router/parser/binary/header.rs
- pgdog/src/frontend/router/parser/binary/mod.rs
- pgdog/src/frontend/router/parser/binary/stream.rs
- pgdog/src/frontend/router/parser/binary/tuple.rs
- pgdog/src/frontend/router/parser/copy.rs
- pgdog/src/frontend/router/parser/error.rs
- pgdog/src/frontend/router/parser/mod.rs
- pgdog/src/frontend/router/parser/query.rs
- pgdog/src/frontend/router/sharding/mod.rs
- pgdog/tests/async_python/pypg.py
Implement binary `COPY`.
Reference: https://www.postgresql.org/docs/current/sql-copy.html#id-1.9.3.55.9.4
#49
> Binary COPY

- integration/pgbench/run.sh
- integration/pgbench/sharded.sql
- integration/setup.sh
- pgdog/src/frontend/router/parser/value.rs
- pgdog/src/frontend/router/parser/where_clause.rs
- Fix handling large integers that encoded as floats in the SQL parser.
- Added pgbench integration tests.
> pgbench integration and fixes

- integration/pgdog.toml
- integration/python/test_asyncpg.py
- pgdog/src/admin/show_pools.rs
- pgdog/src/backend/pool/connection/mod.rs
- pgdog/src/backend/pool/connection/multi_shard.rs
- pgdog/src/backend/server.rs
- pgdog/src/frontend/buffer.rs
- pgdog/src/frontend/client/counter.rs
- pgdog/src/frontend/client/inner.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/prepared_statements/mod.rs
- pgdog/src/frontend/prepared_statements/request.rs
- pgdog/src/frontend/prepared_statements/rewrite.rs
- pgdog/src/net/messages/describe.rs
- pgdog/src/net/messages/mod.rs
- pgdog/src/state.rs
- Handle Describe separately to maintain connection state across multiple shards.
- Check for admin username when connecting.
> More asyncpg tests and fixes

- integration/python/test_asyncpg.py
- integration/python/test_psycopg.py
- pgdog.toml
- pgdog/src/backend/pool/connection/aggregate.rs
- pgdog/src/backend/pool/connection/buffer.rs
- pgdog/src/backend/pool/connection/mod.rs
- pgdog/src/backend/pool/connection/multi_shard/context.rs
- pgdog/src/backend/pool/connection/multi_shard/mod.rs
- pgdog/src/backend/prepared_statements.rs
- pgdog/src/backend/server.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/prepared_statements/global_cache.rs
- pgdog/src/frontend/prepared_statements/mod.rs
- pgdog/src/frontend/prepared_statements/request.rs
- pgdog/src/frontend/prepared_statements/rewrite.rs
- pgdog/src/net/decoder.rs
- pgdog/src/net/messages/bind.rs
- pgdog/src/net/messages/data_row.rs
- pgdog/src/net/messages/data_types/mod.rs
- pgdog/src/net/messages/row_description.rs
- pgdog/src/net/mod.rs
- pgdog/src/net/stream.rs
- Fix binary encoding for COPY in cross shard context
> More binary fixes

- .github/workflows/ci.yml
- .gitignore
- integration/java/dev.sh
- integration/java/pgdog.java
- integration/java/run.sh
> Add Java integration tests

- integration/run.sh
- pgdog/src/backend/databases.rs
- pgdog/src/backend/replication/sharded_tables.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/router/parser/query.rs
Remove allocation from cloning ShardedTables for each query.
> Continue chasing allocs

- .github/workflows/ci.yml
- pgdog.toml
- pgdog/Cargo.toml
- pgdog/src/admin/mod.rs
- pgdog/src/admin/parser.rs
- pgdog/src/admin/show_clients.rs
- pgdog/src/admin/show_lists.rs
- pgdog/src/admin/show_pools.rs
- pgdog/src/admin/show_servers.rs
- pgdog/src/backend/pool/config.rs
- pgdog/src/backend/pool/connection/binding.rs
- pgdog/src/backend/pool/inner.rs
- pgdog/src/backend/pool/monitor.rs
- pgdog/src/backend/pool/pool_impl.rs
- pgdog/src/backend/pool/request.rs
- pgdog/src/backend/pool/state.rs
- pgdog/src/backend/pool/waiting.rs
- pgdog/src/backend/stats.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/comms.rs
- pgdog/src/frontend/connected_client.rs
- pgdog/src/frontend/stats.rs
- pgdog/src/net/parameter.rs
- pgdog/src/util.rs
- Add a bunch of missing fields to `SHOW POOLS`, `SHOW CLIENTS`.
- Added `SHOW LISTS`
- Fix CI build due to CMake 4.0 breaking everything.
> Admin DB improvements

- pgdog.toml
- pgdog/Cargo.toml
- pgdog/src/admin/show_pools.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/comms.rs
- pgdog/src/main.rs
- pgdog/src/stats/clients.rs
- pgdog/src/stats/http_server.rs
- pgdog/src/stats/mod.rs
- pgdog/src/stats/open_metric.rs
- pgdog/src/stats/pools.rs
- Starting OpenMetrics. See #70.
> Starting OpenMetrics

- pgdog/src/backend/pool/connection/mod.rs
> Fix failover for new connections

- .github/workflows/ci.yml
- integration/rust/Cargo.toml
- integration/rust/tests/tokio_postgres/mod.rs
- integration/rust/tests/tokio_postgres/nulls.rs
- pgdog/src/net/messages/bind.rs
> Fix handling nulls in Bind

- pgdog/src/backend/prepared_statements.rs
- pgdog/src/backend/server.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/prepared_statements/rewrite.rs
- Make prepared statements work in session mode (where we don't track them)
> Tweak session mode

- pgdog/src/backend/pool/stats.rs
- pgdog/src/backend/server.rs
- pgdog/src/backend/stats.rs
- pgdog/src/stats/open_metric.rs
- Fix query time and transaction time stats.
> Add query time stats

- integration/toxi/cli.sh
- integration/toxi/setup.sh
- pgdog.toml
- pgdog/Cargo.toml
- pgdog/src/backend/server.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/listener.rs
- pgdog/src/net/mod.rs
- pgdog/src/net/tweaks.rs
> Add TCP timeouts

- pgdog/src/admin/show_config.rs
- pgdog/src/backend/pool/config.rs
- pgdog/src/backend/pool/healthcheck.rs
- pgdog/src/backend/pool/monitor.rs
- pgdog/src/backend/pool/pool_impl.rs
- pgdog/src/config/mod.rs
- pgdog/src/net/messages/row_description.rs
- Add `connect_timeout` for new server connections.
> Add connect timeout

- integration/pgdog.toml
- integration/toxi/setup.sh
- integration/toxi/toxi_spec.rb
- pgdog/src/backend/pool/healthcheck.rs
- pgdog/src/backend/pool/inner.rs
- pgdog/src/backend/pool/pool_impl.rs
- Fix infinite loop in checkout out primary connection that's been banned.
> Fix some bugs

- integration/pgdog.toml
- integration/ruby/lb_spec.rb
Test round robin load balancing.
> Round robin load balancing

- pgdog/src/net/messages/parameter_status.rs
> Server version parameter

- pgdog.toml
- pgdog/src/admin/show_stats.rs
- pgdog/src/backend/pool/stats.rs
- pgdog/src/backend/server.rs
- pgdog/src/backend/stats.rs
- pgdog/src/frontend/router/parser/query.rs
- pgdog/src/frontend/router/parser/route.rs
- Add missing `server_parse_count` and `server_bind_count` stats.
- Add support for `SELECT ... FOR UPDATE` (routed to primary)
> Add missing prepared statements stats

- .github/workflows/package.yml
Reverts pgdogdev/pgdog#119
https://github.com/pgdogdev/pgdog/actions/runs/14652626155/job/41121733721
> Revert "Build arm64 and amd64 images"

- pgdog.toml
- pgdog/src/backend/pool/healthcheck.rs
- pgdog/src/backend/pool/inner.rs
- pgdog/src/backend/pool/mod.rs
- pgdog/src/backend/pool/monitor.rs
- pgdog/src/backend/pool/pool_impl.rs
- pgdog/src/backend/pool/replicas.rs
- pgdog/src/backend/pool/request.rs
- pgdog/src/backend/pool/state.rs
- pgdog/src/backend/pool/stats.rs
- pgdog/src/backend/pool/taken.rs
- pgdog/src/backend/pool/test/mod.rs
- pgdog/src/backend/pool/waiting.rs
- pgdog/tests/pgbench.sh
- Removed a lot of lock contention by rewriting pooling logic. Clients checking connections in will give them directly to clients that are waiting, bypassing an extra lock acquisition.
> 10% speedup

- .github/workflows/package.yml
Use docker buildx for multi platform build
Reference build: https://github.com/sandangel/pgdog/actions/runs/14945641748/job/41990218584
Signed-off-by: San Nguyen <vinhsannguyen91@gmail.com>
> ci: add linux arm64 build

- integration/rust/tests/integration/auth.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/net/messages/auth/password.rs
> Fix trust auth requiring password with passthrough auth

- .github/workflows/ci.yml
- integration/pgbench/dev.sh
- pgdog/src/backend/pool/connection/multi_shard/mod.rs
- pgdog/src/backend/pool/connection/multi_shard/test.rs
- pgdog/src/frontend/buffer.rs
- pgdog/src/frontend/router/parser/query.rs
- pgdog/src/net/decoder.rs
Adding tests to multi-shard queries.
> Add some tests to multi-shard queries

- integration/rust/tests/integration/fake_transactions.rs
- pgdog/src/backend/pool/cleanup.rs
- pgdog/src/backend/pool/connection/mirror.rs
- pgdog/src/backend/pool/connection/mod.rs
- pgdog/src/backend/pool/inner.rs
- pgdog/src/backend/server.rs
- pgdog/src/frontend/router/parser/query.rs
- pgdog/src/net/messages/bind.rs
- pgdog/src/net/messages/parse.rs
- pgdog/src/net/messages/query.rs
- pgdog/src/net/parameter.rs
- Compare parameters correctly, discarding old values and setting new ones. Handles edge cases, where servers have parameters clients don't.
> Fix params synchronization

- pgdog/src/admin/show_servers.rs
- pgdog/src/backend/pool/inner.rs
- pgdog/src/backend/pool/monitor.rs
- pgdog/src/backend/pool/pool_impl.rs
- pgdog/src/backend/pool/stats.rs
- pgdog/src/backend/server.rs
- pgdog/src/backend/stats.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/client/test/mod.rs
- Fixed double counting server assignment stats.
- Tracking healthcheck stats.
> More client/server integration tests

- integration/go/pg_tests_test.go
> More golang tests

- README.md
> Fix logo on light mode

- examples/demo/src/main.rs
- pgdog/src/admin/ban.rs
- pgdog/src/admin/set.rs
- pgdog/src/backend/pool/inner.rs
- pgdog/src/backend/replication/sharded_tables.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/client/test/mod.rs
- pgdog/src/frontend/router/parser/copy.rs
- pgdog/src/frontend/router/parser/function.rs
- pgdog/src/frontend/router/parser/insert.rs
- pgdog/src/frontend/router/parser/query.rs
- pgdog/src/frontend/router/parser/route.rs
- pgdog/src/frontend/router/parser/value.rs
- pgdog/src/frontend/router/sharding/context.rs
- pgdog/src/frontend/router/sharding/tables.rs
- pgdog/src/frontend/router/sharding/test/mod.rs
- pgdog/src/frontend/router/sharding/value.rs
- pgdog/src/stats/logger.rs
- pgdog/src/stats/open_metric.rs
1. Make sure we check CTEs for write queries.
> Handle CTEs

- README.md
As discussed in Discord.
Depends on https://github.com/pgdogdev/pgdog/pull/203, maybe?
> readme: add docs for command line options

- integration/go/go_pgx/pg_tests_test.go
- pgdog/src/backend/pool/connection/mirror.rs
- pgdog/src/frontend/client/inner.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/client/test/mod.rs
- pgdog/src/frontend/router/context.rs
- pgdog/src/frontend/router/mod.rs
- pgdog/src/frontend/router/parser/query.rs
If a prepared statement is sent inside a transaction, make sure the router knows about the transaction.
> Fix incorrect transaction routing

- pgdog/src/backend/databases.rs
- pgdog/src/backend/pool/cluster.rs
- pgdog/src/frontend/router/parser/query.rs
- Add warning when databases are configured in session mode but will require routing features only available in transaction mode. #184
> Add warning for session mode

- pgdog/src/admin/error.rs
- pgdog/src/admin/mod.rs
- pgdog/src/admin/parser.rs
- pgdog/src/admin/probe.rs
- pgdog/src/backend/pool/address.rs
- `PROBE` admin command that tests a connection to a Postgres backend and returns the latency between PgDog and the server.
> Probe admin command

- pgdog/src/backend/pool/monitor.rs
- pgdog/src/backend/server.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/net/stream.rs
- pgdog/src/net/tweaks.rs
Better debug logging experience.
> More manageable debug logger

- integration/go/go_pgx/pg_tests_test.go
- pgdog/src/frontend/client/engine/mod.rs
- pgdog/src/frontend/prepared_statements/mod.rs
- pgdog/src/net/messages/close.rs
Remove statement from local prepared statement cache when client sends `Close`.
> Remove statements from client local mapping

- integration/go/go_pgx/pg_tests_test.go
- integration/rust/tests/integration/mod.rs
- integration/rust/tests/integration/prepared.rs
- pgdog/src/admin/mod.rs
- pgdog/src/admin/named_row.rs
- pgdog/src/admin/prelude.rs
- pgdog/src/admin/show_clients.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/prepared_statements/mod.rs
- pgdog/src/frontend/prepared_statements/rewrite.rs
- pgdog/src/frontend/stats.rs
1. Add `prepared_statements` counter in `SHOW CLIENTS`
2. Add filter to columns in `SHOW CLIENTS`, e.g. ` SHOW CLIENTS prepared_statements` will only show that column (plus some mandatory ones)
> Prepared statements counter

- Cargo.lock
- pgdog/Cargo.toml
- pgdog/src/backend/prepared_statements.rs
Use LRU instead of random algorithm for server prepared statement eviction.
> Use LRU for prepared statement eviction on the server

- pgdog/src/backend/databases.rs
- pgdog/src/backend/pool/cluster.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/router/sharding/context_builder.rs
- pgdog/src/frontend/router/sharding/error.rs
- pgdog/src/frontend/router/sharding/list.rs
- pgdog/src/frontend/router/sharding/mapping.rs
- pgdog/src/frontend/router/sharding/mod.rs
- pgdog/src/frontend/router/sharding/range.rs
- pgdog/src/frontend/router/sharding/test/mod.rs
Make list sharding more efficient using a hashmap O(1) instead of linear search.
> Tune list sharding

- pgdog/src/backend/pool/monitor.rs
> Log connection attempt

- pgdog/src/frontend/router/parser/cache.rs
- Fix panic in `SHOW QUERY_CACHE;`.
> Fix panic in show query cache

- pgdog/src/backend/error.rs
- pgdog/src/backend/server.rs
- pgdog/src/config/mod.rs
- pgdog/src/net/tls.rs
> Add configuration value for tls verification and optional cert path

- pgdog/src/backend/server.rs
- pgdog/src/net/tls.rs
Demote some log lines to debug, normalize others.
> Logging tweaks for TLS

- CONTRIBUTING.md
Ran into some issues which we worked through, this is the doc update resulting
> Update contrib info for easier first test runs

- Makefile
> [chore] Add reload command to make file

- integration/logical/reset.sh
- pgdog/src/backend/replication/logical/error.rs
- pgdog/src/backend/replication/logical/publisher/mod.rs
- pgdog/src/backend/replication/logical/publisher/parallel_sync.rs
- pgdog/src/backend/replication/logical/publisher/publisher_impl.rs
- pgdog/src/backend/replication/logical/publisher/table.rs
Parallelize table sync using multiple replicas and maximum concurrency.
TODO: test this in CI.
> Parallel table sync

- integration/pub_sub/pgdog.toml
- pgdog/src/backend/pool/connection/mod.rs
- pgdog/src/backend/pub_sub/listener.rs
Amend #301 to survive `RELOAD` and `RECONNECT`.
> Listener survive reload

- example.pgdog.toml
- pgdog/src/cli.rs
- pgdog/src/main.rs
- offloads to our current config parsing.
- caught 2 errors in example.pgdog.toml
> Add config check cli command

- pgdog/src/backend/pub_sub/listener.rs
> Fix compiler error

- integration/python/test_prepared.py
- Add test for rewriting prepared statements inside transactions.
> Test rewrite inside transactions

- pgdog/src/admin/show_query_cache.rs
- Fix deadlock in `SHOW QUERY_CACHE`
- Add test
> Fix deadlock in show query_cache

- pgdog/src/backend/error.rs
> Print toml error on reload

- pgdog/src/backend/schema/sync/pg_dump.rs
- pgdog/src/cli.rs
Sync foreign keys and indexes that we skipped for initial data sync.
> [Resharding] Sync indexes, foreign keys

- pgdog/src/backend/schema/sync/mod.rs
- pgdog/src/backend/schema/sync/pg_dump.rs
- pgdog/src/backend/schema/sync/progress.rs
- pgdog/src/cli.rs
- pgdog/src/frontend/router/parser/table.rs
Show progress for data sync. Helps with slow queries like `CREATE INDEX`.
> [Resharding] Show progress for schema sync

- .github/workflows/ci.yml
- integration/common.sh
- integration/dry_run/.gitignore
- integration/dry_run/dev.sh
- integration/dry_run/package-lock.json
- integration/dry_run/package.json
- integration/dry_run/pgdog.toml
- integration/dry_run/run.sh
- integration/dry_run/test/sequelize.js
- integration/dry_run/users.toml
- pgdog/src/frontend/client/inner.rs
- pgdog/src/frontend/router/parser/cache.rs
- pgdog/src/frontend/router/parser/context.rs
- pgdog/src/frontend/router/parser/insert.rs
- pgdog/src/frontend/router/parser/query/mod.rs
- pgdog/src/frontend/router/sharding/value.rs
- pgdog/src/main.rs
- pgdog/src/plugin/mod.rs
Add `dry_run` back into query parser after refactor
> Dry run enable parser

- pgdog/src/frontend/router/parser/copy.rs
- pgdog/src/frontend/router/parser/csv/mod.rs
- pgdog/src/frontend/router/parser/csv/record.rs
> Handle NULL string parameter in COPY

- integration/pgdog.toml
- integration/rust/tests/integration/mod.rs
- integration/rust/tests/integration/set_sharding_key.rs
- integration/users.toml
- pgdog/src/backend/replication/sharded_tables.rs
- pgdog/src/config/mod.rs
- pgdog/src/frontend/router/parser/comment.rs
- pgdog/src/frontend/router/parser/error.rs
- pgdog/src/frontend/router/parser/query/set.rs
- pgdog/src/frontend/router/parser/query/test.rs
- pgdog/src/frontend/router/sharding/context_builder.rs
- pgdog/src/frontend/router/sharding/error.rs
- pgdog/src/frontend/router/sharding/list.rs
- pgdog/src/frontend/router/sharding/mapping.rs
> Automatically detect sharding function when there is only one

- Cargo.lock
- pgdog-plugin/Cargo.toml
- pgdog/Cargo.toml
- plugins/pgdog-example-plugin/Cargo.toml
- Bump `pg_query` to `6.1.1` to fix docs.rs issue.
> Bump pg_query

- .github/workflows/package.yml
- Cargo.lock
- pgdog/Cargo.toml
Fix tag on GitHub package...hopefully.
> Fix tag on GitHub package

- .github/workflows/ci.yml
- Use slightly smaller CI box.
> Use 4 cores for CI

- pgdog/src/config/mod.rs
> General env config converted, a few env tests

- pgdog/src/backend/server.rs
> demote no TLS warning to debug (when TlsVerify::None)

- pgdog/src/backend/schema/sync/pg_dump.rs
- pgdog/src/backend/schema/sync/progress.rs
- pgdog/src/cli.rs
Log which table pg_dump is currently dumping.
> Log which table we fetch schema for

- Cargo.lock
- pgdog/Cargo.toml
> Release v0.1.8

- pgdog/src/frontend/router/parser/query/select.rs
- Fix unsharded/direct-to-shard performance regression caused by cross-shard query rewrites.
> Fix direct-to-shard performance regression

- pgdog/src/backend/pool/guard.rs
- pgdog/src/backend/pool/test/mod.rs
- pgdog/src/backend/prepared_statements.rs
- pgdog/src/backend/server.rs
Implement extended protocol error recovery correctly. Commands after error are ignored until Sync is received.
> Correctly handle extended error state

- pgdog/src/frontend/router/parser/rewrite_engine.rs
> Avoid cloning AST until later in the rewrite process, where its modified

- integration/rust/tests/integration/mod.rs
- integration/rust/tests/integration/savepoint.rs
- pgdog/src/frontend/client/mod.rs
- pgdog/src/frontend/client/query_engine/query.rs
- pgdog/src/frontend/router/parser/query/transaction.rs
- pgdog/src/frontend/router/parser/route.rs
> Support savepoints
